vich_uploader:
    db_driver: orm
    twig: false
    mappings:
        medias:
            uri_prefix: /contents/medias
            upload_destination: '%kernel.project_dir%/public/contents/medias'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true